steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t',
            '${_CLOUD_RUN_IMAGE}',
            '.'
          ]
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_CLOUD_RUN_IMAGE}']
    # Deploy container image to Cloud Run

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '${_CLOUD_RUN_SERVICE}'
    - '--image'
    - '${_CLOUD_RUN_IMAGE}'
    - '--region'
    - '${_CLOUD_RUN_REGION}'

images:
  - '${_CLOUD_RUN_IMAGE}'

substitutions:
  _PROJECT: build-zenetics
  _CLOUD_RUN_SERVICE: 'zenetics-docs'
  _CLOUD_RUN_REGION: 'europe-west1'
  _IMAGE_TAG: 'latest'
  _CLOUD_RUN_IMAGE: 'europe-west3-docker.pkg.dev/${_PROJECT}/docker-registry/${_CLOUD_RUN_SERVICE}:${_IMAGE_TAG}'

logsBucket: 'build-zenetics-cloudbuild-logs'
options:
  logging: GCS_ONLY
  dynamicSubstitutions: true

